x<-c(21,62,30,53)
labels<-c("London","New Yor","Singapore","Munbai")
piedegree=round(x*360/sum(x),2)
piepercent<-round(100*x/sum(x),2)
pie(x,labels= piepercent,main = "City Pie Chart",col = rainbow(length(x)))
legend("topright",c("London","New Yor","Singapore","Munbai"),cex=0.8,fill=rainbow(length(x)))
install.packages("plotrix")       
library(plotrix)
pie3D(x,explode = 0.1,labels = piepercent,main="City Pie Chart")
